# Generated by Django 3.0.7 on 2020-06-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
