# Generated by Django 3.0.7 on 2020-06-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='id_post',
        ),
    ]
