# Generated by Django 3.0.7 on 2020-06-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comments_amount',
        ),
    ]
