# Generated by Django 3.0.7 on 2020-06-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20200630_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments_amount',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
